### ISSUE TITLE
DLL load failed: 指定されたモジュールが見つかりません。

### ISSUE THREAD

**Issue by tanaka-jp** [studio-ousia/mojimoji#17]
インストールはできましたが、
pip install mojimoji

Collecting mojimoji
  Using cached mojimoji-0.0.11-cp36-cp36m-win_amd64.whl (35 kB)
Installing collected packages: mojimoji
Successfully installed mojimoji-0.0.11

import時にエラーが起きました。

Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import mojimoji
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: 指定されたモジュールが見つかりません。

**Comment by kzh22** [comment]
同じ問題が起きています

Collecting mojimoji
  Using cached mojimoji-0.0.11-cp38-cp38-win_amd64.whl (35 kB)
Installing collected packages: mojimoji
Successfully installed mojimoji-0.0.11

Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mojimoji
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing mojimoji: 指定されたモジュールが見つかりません。

**Comment by kzh22** [comment]
C:\Users\---\Anaconda3\Lib\site-packages\mojimoji
内のファイル名が
__init__.pyi
となっていました。

__init__.py
に変更し無事動きまた。

**Comment by tamuhey** [comment]
@tanaka-jp @kzh22 `pip install mojimoji==0.0.9`とするとどうなりますか？

**Comment by masaru-tsuruta** [comment]
同じく、pip install mojimojiを実行しインストールは完了しましたが、
import mojimojiを行うと、「DLL Load failed: 指定されたモジュールがみつかりません。」のエラーが生じました。
pythonのバージョンは、3.7.6で、Windows10 OSです。
同じバージョンの他の端末は問題なく動いていますが、何か設定等必要でしょうか。
ちなみにversionを0.0.9.post0にすると動くことは確認できています。よろしくお願いいたします。

**Comment by tamuhey** [comment]
@masaru-tsuruta `

> 同じバージョンの他の端末は問題なく動いていますが、何か設定等必要でしょうか。

「他の端末」はWindowsでしょうか？

**Comment by masaru-tsuruta** [comment]
@tamuhey 
他の端末もWindowsです。よろしくお願い致します。

**Comment by tamuhey** [comment]
@masaru-tsuruta 出力されるエラーログを全て貼っていただくことは可能ですか？

**Comment by masaru-tsuruta** [comment]
@tamuhey
お世話になっております。以下のエラーが表示されます。宜しくお願い致します。
>>> import mojimoji
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: 指定されたモジュールが見つかりません。

**Comment by tamuhey** [comment]
@masaru-tsuruta ありがとうございます。
コマンドプロンプト上で、`python -v -c "import mojimoji"` とうつとどうなるでしょうか？とても長いログが出力されますが、貼っていただけるとありがたいです。

**Comment by masaru-tsuruta** [comment]
@tamuhey
ありがとうございます。こちらのログになります。
```
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# C:\ProgramData\Anaconda3\lib\encodings\__pycache__\__init__.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\encodings\__init__.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\encodings\\__pycache__\\__init__.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\codecs.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\codecs.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2C8C3E48>
# C:\ProgramData\Anaconda3\lib\encodings\__pycache__\aliases.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\encodings\aliases.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\encodings\\__pycache__\\aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E920D48>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2C8BEFC8>
# C:\ProgramData\Anaconda3\lib\encodings\__pycache__\utf_8.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\encodings\utf_8.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\encodings\\__pycache__\\utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E933148>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\ProgramData\Anaconda3\lib\encodings\__pycache__\latin_1.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\encodings\latin_1.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\encodings\\__pycache__\\latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E9339C8>
# C:\ProgramData\Anaconda3\lib\__pycache__\io.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\io.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\io.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\abc.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\abc.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E938548>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E933A48>
# C:\ProgramData\Anaconda3\lib\__pycache__\site.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\site.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\site.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\os.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\os.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\os.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\stat.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\stat.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E9578C8>
# C:\ProgramData\Anaconda3\lib\__pycache__\ntpath.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\ntpath.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\ntpath.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\genericpath.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\genericpath.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E9628C8>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E95A608>
# C:\ProgramData\Anaconda3\lib\__pycache__\_collections_abc.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\_collections_abc.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E968488>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E9478C8>
# C:\ProgramData\Anaconda3\lib\__pycache__\_sitebuiltins.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\_sitebuiltins.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E947E88>
# C:\ProgramData\Anaconda3\lib\__pycache__\_bootlocale.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\_bootlocale.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E94D388>
# C:\ProgramData\Anaconda3\lib\encodings\__pycache__\cp932.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\encodings\cp932.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\encodings\\__pycache__\\cp932.cpython-37.pyc'
import '_codecs_jp' # <class '_frozen_importlib.BuiltinImporter'>
import '_multibytecodec' # <class '_frozen_importlib.BuiltinImporter'>
import 'encodings.cp932' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E955848>
# C:\ProgramData\Anaconda3\lib\__pycache__\types.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\types.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\types.cpython-37.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA2BA48>
# C:\ProgramData\Anaconda3\lib\importlib\__pycache__\__init__.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\importlib\__init__.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\importlib\\__pycache__\\__init__.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\warnings.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\warnings.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\warnings.cpython-37.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA36308>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA31AC8>
# C:\ProgramData\Anaconda3\lib\importlib\__pycache__\util.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\importlib\util.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\importlib\\__pycache__\\util.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\importlib\__pycache__\abc.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\importlib\abc.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\importlib\\__pycache__\\abc.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\importlib\__pycache__\machinery.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\importlib\machinery.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\importlib\\__pycache__\\machinery.cpython-37.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA47A88>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA42488>
# C:\ProgramData\Anaconda3\lib\__pycache__\contextlib.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\contextlib.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\contextlib.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\collections\__pycache__\__init__.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\collections\__init__.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\collections\\__pycache__\\__init__.cpython-37.pyc'
# C:\ProgramData\Anaconda3\lib\__pycache__\operator.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\operator.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\operator.cpython-37.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EB80C08>
# C:\ProgramData\Anaconda3\lib\__pycache__\keyword.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\keyword.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\keyword.cpython-37.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EB82A48>
# C:\ProgramData\Anaconda3\lib\__pycache__\heapq.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\heapq.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\heapq.cpython-37.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EB8E608>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\ProgramData\Anaconda3\lib\__pycache__\reprlib.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\reprlib.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\reprlib.cpython-37.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EB83788>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA5DB48>
# C:\ProgramData\Anaconda3\lib\__pycache__\functools.cpython-37.pyc matches C:\ProgramData\Anaconda3\lib\functools.py
# code object from 'C:\\ProgramData\\Anaconda3\\lib\\__pycache__\\functools.cpython-37.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EB633C8>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA470C8>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2EA3C3C8>
# possible namespace for C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits
# destroy sphinxcontrib
# destroy sphinxcontrib
# destroy sphinxcontrib
# destroy sphinxcontrib
# destroy sphinxcontrib
# destroy sphinxcontrib
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x0000014C2E93DD88>
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 指定されたモジュールが見つかりません。
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing zipimport
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing winreg
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# destroy io
# cleanup[2] removing abc
# cleanup[2] removing _abc
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing ntpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing encodings.cp932
# cleanup[2] removing _codecs_jp
# cleanup[2] removing _multibytecodec
# cleanup[2] removing types
# cleanup[2] removing importlib
# destroy importlib
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing warnings
# cleanup[2] removing importlib.util
# cleanup[2] removing importlib.abc
# cleanup[2] removing importlib.machinery
# cleanup[2] removing contextlib
# destroy contextlib
# cleanup[2] removing collections
# destroy collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing mpl_toolkits
# destroy mpl_toolkits
# cleanup[2] removing sphinxcontrib
# destroy sphinxcontrib
# destroy zipimport
# destroy _signal
# destroy _sitebuiltins
# destroy ntpath
# destroy _stat
# destroy genericpath
# destroy os
# destroy stat
# destroy _locale
# destroy importlib.util
# destroy importlib.abc
# destroy functools
# destroy types
# destroy importlib.machinery
# destroy warnings
# destroy abc
# destroy _collections_abc
# destroy heapq
# destroy _operator
# destroy _heapq
# destroy itertools
# destroy _collections
# destroy _abc
# destroy _functools
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _thread
# cleanup[3] wiping _warnings
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping nt
# cleanup[3] wiping winreg
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping encodings.cp932
# cleanup[3] wiping _codecs_jp
# destroy _codecs_jp
# cleanup[3] wiping _multibytecodec
# cleanup[3] wiping importlib._bootstrap
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
```

**Comment by tamuhey** [comment]
@masaru-tsuruta なるほど、わからないですね、、下のCIにあるように、ソースからビルドすることはできますか？
https://github.com/studio-ousia/mojimoji/blob/master/.github/workflows/build.yml

**Comment by Lbzttt** [comment]
少し前に同じエラーが出るようになりましたがVisual C++ ランタイムライブラリ 再頒布可能パッケージの再インストールで解決しました。
参考までに。

**Comment by masaru-tsuruta** [comment]
@tamuhey 
ご調査有難うございます。私の知識不足で申し訳ないですが、ソースからのビルドがこちらのリンクだけからは方法がわからず、お手数ですが少し補足いただけますと幸いです。（※恐縮ですが、記載お手数であれば先に以下のC++のパッケージの方は早速試してみるので、こちらの結果を待っていただいても大丈夫です。）
別の方が記載いただいたVisual C++ ランタイムライブラリ 再頒布可能パッケージも試してみます。

@Lbzttt 有難うございます。試してみます。

**Comment by masaru-tsuruta** [comment]
@tamuhey @Lbzttt 
vc_redist.x64.exeのインストールでエラー事象が解消しました。
大変助かりました。お礼申し上げます。
